INSERT INTO  EMPLOYEE
VALUES (1, 'Петя');

INSERT INTO  EMPLOYEE
VALUES (2, 'Вася');

INSERT INTO  EMPLOYEE
VALUES (3, 'Эммануэль');

CREATE SEQUENCE IF NOT EXISTS EMPLOYEE_SEQ START WITH 4 INCREMENT BY 1;

COMMIT;

INSERT INTO ISSUE
VALUES (1, 'Не работает сканер', 1, 1);

INSERT INTO ISSUE
VALUES (2, 'Не работает принтер', 2, 2);

INSERT INTO ISSUE
VALUES (3, 'Не работает плоттер', 2, 2);

INSERT INTO ISSUE
VALUES (4, 'Не работает шреддер', 3, 3);

INSERT INTO ISSUE
VALUES (5, 'Не работает ничего', 4, null);

CREATE SEQUENCE IF NOT EXISTS ISSUE_SEQ START WITH 6 INCREMENT BY 1;

COMMIT;